// Generated by gencpp from file custom_msg/AprilTagPosition.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSG_MESSAGE_APRILTAGPOSITION_H
#define CUSTOM_MSG_MESSAGE_APRILTAGPOSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace custom_msg
{
template <class ContainerAllocator>
struct AprilTagPosition_
{
  typedef AprilTagPosition_<ContainerAllocator> Type;

  AprilTagPosition_()
    : header()
    , id(0)
    , camera_position()
    , world_position()  {
    }
  AprilTagPosition_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , id(0)
    , camera_position(_alloc)
    , world_position(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _camera_position_type;
  _camera_position_type camera_position;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _world_position_type;
  _world_position_type world_position;





  typedef boost::shared_ptr< ::custom_msg::AprilTagPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msg::AprilTagPosition_<ContainerAllocator> const> ConstPtr;

}; // struct AprilTagPosition_

typedef ::custom_msg::AprilTagPosition_<std::allocator<void> > AprilTagPosition;

typedef boost::shared_ptr< ::custom_msg::AprilTagPosition > AprilTagPositionPtr;
typedef boost::shared_ptr< ::custom_msg::AprilTagPosition const> AprilTagPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msg::AprilTagPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msg::AprilTagPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msg::AprilTagPosition_<ContainerAllocator1> & lhs, const ::custom_msg::AprilTagPosition_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.id == rhs.id &&
    lhs.camera_position == rhs.camera_position &&
    lhs.world_position == rhs.world_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msg::AprilTagPosition_<ContainerAllocator1> & lhs, const ::custom_msg::AprilTagPosition_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msg::AprilTagPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msg::AprilTagPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg::AprilTagPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg::AprilTagPosition_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg::AprilTagPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg::AprilTagPosition_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msg::AprilTagPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd61561e1ae547a5df703150da4f40e2";
  }

  static const char* value(const ::custom_msg::AprilTagPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd61561e1ae547a5ULL;
  static const uint64_t static_value2 = 0xdf703150da4f40e2ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msg::AprilTagPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msg/AprilTagPosition";
  }

  static const char* value(const ::custom_msg::AprilTagPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msg::AprilTagPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# AprilTagPosition.msg\n"
"\n"
"# ROS message for representing the position of an AprilTag\n"
"# relative to the camera and in the world coordinate frame\n"
"\n"
"std_msgs/Header header              # Standard ROS message header\n"
"\n"
"int32 id                  # ID of the AprilTag\n"
"\n"
"geometry_msgs/Point camera_position  # Position of the AprilTag relative to the camera\n"
"geometry_msgs/Point world_position   # Position of the AprilTag in the world coordinate frame\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::custom_msg::AprilTagPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msg::AprilTagPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.id);
      stream.next(m.camera_position);
      stream.next(m.world_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AprilTagPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msg::AprilTagPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msg::AprilTagPosition_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "camera_position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.camera_position);
    s << indent << "world_position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.world_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSG_MESSAGE_APRILTAGPOSITION_H
